// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"testEntGo/ent/clothe"
	"testEntGo/ent/people"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClotheCreate is the builder for creating a Clothe entity.
type ClotheCreate struct {
	config
	mutation *ClotheMutation
	hooks    []Hook
}

// SetType sets the "type" field.
func (cc *ClotheCreate) SetType(s string) *ClotheCreate {
	cc.mutation.SetType(s)
	return cc
}

// SetColor sets the "color" field.
func (cc *ClotheCreate) SetColor(s string) *ClotheCreate {
	cc.mutation.SetColor(s)
	return cc
}

// SetBuyDate sets the "buy_date" field.
func (cc *ClotheCreate) SetBuyDate(t time.Time) *ClotheCreate {
	cc.mutation.SetBuyDate(t)
	return cc
}

// SetOwnerID sets the "owner" edge to the People entity by ID.
func (cc *ClotheCreate) SetOwnerID(id int) *ClotheCreate {
	cc.mutation.SetOwnerID(id)
	return cc
}

// SetNillableOwnerID sets the "owner" edge to the People entity by ID if the given value is not nil.
func (cc *ClotheCreate) SetNillableOwnerID(id *int) *ClotheCreate {
	if id != nil {
		cc = cc.SetOwnerID(*id)
	}
	return cc
}

// SetOwner sets the "owner" edge to the People entity.
func (cc *ClotheCreate) SetOwner(p *People) *ClotheCreate {
	return cc.SetOwnerID(p.ID)
}

// Mutation returns the ClotheMutation object of the builder.
func (cc *ClotheCreate) Mutation() *ClotheMutation {
	return cc.mutation
}

// Save creates the Clothe in the database.
func (cc *ClotheCreate) Save(ctx context.Context) (*Clothe, error) {
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ClotheCreate) SaveX(ctx context.Context) *Clothe {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ClotheCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ClotheCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ClotheCreate) check() error {
	if _, ok := cc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Clothe.type"`)}
	}
	if _, ok := cc.mutation.Color(); !ok {
		return &ValidationError{Name: "color", err: errors.New(`ent: missing required field "Clothe.color"`)}
	}
	if _, ok := cc.mutation.BuyDate(); !ok {
		return &ValidationError{Name: "buy_date", err: errors.New(`ent: missing required field "Clothe.buy_date"`)}
	}
	return nil
}

func (cc *ClotheCreate) sqlSave(ctx context.Context) (*Clothe, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ClotheCreate) createSpec() (*Clothe, *sqlgraph.CreateSpec) {
	var (
		_node = &Clothe{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(clothe.Table, sqlgraph.NewFieldSpec(clothe.FieldID, field.TypeInt))
	)
	if value, ok := cc.mutation.GetType(); ok {
		_spec.SetField(clothe.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := cc.mutation.Color(); ok {
		_spec.SetField(clothe.FieldColor, field.TypeString, value)
		_node.Color = value
	}
	if value, ok := cc.mutation.BuyDate(); ok {
		_spec.SetField(clothe.FieldBuyDate, field.TypeTime, value)
		_node.BuyDate = value
	}
	if nodes := cc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clothe.OwnerTable,
			Columns: []string{clothe.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(people.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.people_clothes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClotheCreateBulk is the builder for creating many Clothe entities in bulk.
type ClotheCreateBulk struct {
	config
	err      error
	builders []*ClotheCreate
}

// Save creates the Clothe entities in the database.
func (ccb *ClotheCreateBulk) Save(ctx context.Context) ([]*Clothe, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Clothe, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClotheMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ClotheCreateBulk) SaveX(ctx context.Context) []*Clothe {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ClotheCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ClotheCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
