// Code generated by ent, DO NOT EDIT.

package ent

import (
	"testEntGo/ent/group"
	"testEntGo/ent/people"
	"testEntGo/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	groupFields := schema.Group{}.Fields()
	_ = groupFields
	// groupDescName is the schema descriptor for name field.
	groupDescName := groupFields[0].Descriptor()
	// group.NameValidator is a validator for the "name" field. It is called by the builders before save.
	group.NameValidator = groupDescName.Validators[0].(func(string) error)
	peopleFields := schema.People{}.Fields()
	_ = peopleFields
	// peopleDescAge is the schema descriptor for age field.
	peopleDescAge := peopleFields[2].Descriptor()
	// people.AgeValidator is a validator for the "age" field. It is called by the builders before save.
	people.AgeValidator = peopleDescAge.Validators[0].(func(int) error)
}
