// Code generated by ent, DO NOT EDIT.

package clothe

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the clothe type in the database.
	Label = "clothe"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldColor holds the string denoting the color field in the database.
	FieldColor = "color"
	// FieldBuyDate holds the string denoting the buy_date field in the database.
	FieldBuyDate = "buy_date"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// Table holds the table name of the clothe in the database.
	Table = "clothes"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "clothes"
	// OwnerInverseTable is the table name for the People entity.
	// It exists in this package in order to avoid circular dependency with the "people" package.
	OwnerInverseTable = "peoples"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "people_clothes"
)

// Columns holds all SQL columns for clothe fields.
var Columns = []string{
	FieldID,
	FieldType,
	FieldColor,
	FieldBuyDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "clothes"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"people_clothes",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Clothe queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByColor orders the results by the color field.
func ByColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldColor, opts...).ToFunc()
}

// ByBuyDate orders the results by the buy_date field.
func ByBuyDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBuyDate, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
